export const webPortfolio = [
  // {
  //   id: 1,
  //   name: "Chat App",
  //   img: chat,
  //   desc: "ZiltChat is  chatting app,  friendly environment for you to chat with others, whether you're looking for new friends, a casual conversation, or a meaningful connection.You can create your own profile, upload photos, and start chatting instantly with our private messaging system. ",
  //   stack: ["Javascript", "React Js ", "Tailwind CSS", "Google Firebase"],
  //   github: "https://github.com/mr-atuzie/chatting_app",
  //   link: "https://main--golden-boba-1b00ba.netlify.app/",
  // },
  {
    id: 2,
    name: "E-commerce App",
    img: "",
    desc: "E-commerce app,an online platform where businesses can sell their products and services to customers through the internet. The website include a shopping cart feature ,a secure payment gateway that allows customers to make payments",
    stack: ["Javascript", "React Js ", "Tailwind CSS", "Redux"],
    github: "https://github.com/mr-atuzie/e-commerce",
    link: "https://scintillating-gumdrop-389a23.netlify.app/",
  },
  {
    id: 4,
    name: "Listing/ Rent App",
    // img: realtor,
    desc: "Realtor a real estate listings website that allows homeowners, real estate agents, and developers to list and advertise properties for sale or rent. These sites provide a central location where potential buyers or renters can browse through available properties, view photos, and contact the seller or agent for more information.",
    stack: ["Javascript", "React Js ", "Tailwind CSS"],
    github: "https://github.com/mr-atuzie/realtor",
    link: "https://whimsical-paletas-07010e.netlify.app/",
  },
  {
    id: 5,
    name: "Business Portfolio",
    // img: biz,
    desc: "A business site /online platform that allows businesses to showcase their products or services, interact with customers, and conduct transactions. These sites provide a central location where potential customers can learn more about the business, view products or services, and make purchases or inquiries.",
    stack: ["Javascript", "React Js ", "Tailwind CSS"],
    github: "https://github.com/mr-atuzie/edge",
    link: "https://splendorous-smakager-d3f3b4.netlify.app/",
  },
  {
    id: 3,
    name: "Exams App",
    img: "",
    desc: "A computer base test application for writing multiple exams , getting instanst results , grading user performance and also sending certification to user email",
    stack: ["Javascript", "React Js ", "Tailwind CSS", "Redux"],
    github: "https://github.com/mr-atuzie/cbt",
    link: "https://endearing-otter-5dbb9f.netlify.app/",
  },

  {
    id: 6,
    name: "Business Portfolio (landing page)",
    // img: p1,
    desc: " Super is a subscription service that provides care and repaire for your home.",
    stack: ["Javascript", "React Js ", "Tailwind CSS"],
    github: "https://github.com/mr-atuzie/super_landing-page",
    link: "https://genuine-flan-11fc86.netlify.app/",
  },
];
